START
dataType  Signal
studyGen    1
dumpGenInfo 0
studyOffline  0
checkL1Offline 0
applyIso 0
histFile  PU200_study_30_10/Signal_pu200_medium_baseline_Bsmass51_57_BsPt_11_phimass_99_104_dz06_dxy05.root
logFile   PU200_study_30_10/Signal_pu200_medium_baseline_Bsmass51_57_BsPt_11_phimass_99_104_dz06_dxy05.out
maxEvent -1
verbosity 0
applyTrackQuality 1
trkSelCuts maxTrkEta=2.5 minTrkPt=2.0 maxTrkChi2=20 minTrkLayers=4 minTrkPSLayers=2
phiSelCuts maxTrkPairDz=0.6 maxTrkPairDxy=0.5 massLow=0.99 massHigh=1.04
bsSelCuts maxPhiPairDxy=0.5 maxPhiPairDz=0.6 minPhiPairDr=0.2 maxPhiPairDr=1.0 maxPhiTrkDr=0.12 massLow=5.1 massHigh=5.7
isoCuts isoCone=0.4 maxIso=0.8 isoInnerCone=0
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_19.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_2.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_31.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_8.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_5.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_3.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_6.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_24.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_1.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_9.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_14.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_10.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_13.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_34.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_22.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_21.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_7.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_20.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_29.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_17.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_27.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_4.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_28.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_11.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_15.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_35.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_23.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_16.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_18.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_12.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_33.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_25.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_32.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_30.root
inputFile /eos/user/s/subiran/L1TTDR/BsToPhiPhi/L1/PU200/BsToPhiPhi_PU200_26.root
END
