START
dataType  Signal
studyGen    1
dumpGenInfo 0
studyOffline 0
histFile  PU140/Signal_pu140_loose_baseline_4August_2018.root
logFile   PU140/Signal_pu140_loose_baseline_4August_2018.out
maxEvent -1
verbosity 0
applyTrackQuality 0
trkSelCuts maxTrkEta=2.5 minTrkPt=2.0 maxTrkChi2=20 minTrkLayers=4 minTrkPSLayers=2
phiSelCuts maxTrkPairDz=1.0 maxTrkPairDxy=1.0 massLow=0.99 massHigh=1.04
bsSelCuts maxPhiPairDxy=1.0 maxPhiPairDz=1.0 minPhiPairDr=0.2 maxPhiPairDr=1.0 maxPhiTrkDr=0.12 massLow=5.27 massHigh=5.49
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_18.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_7.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_1.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_3.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_11.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_13.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_17.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_4.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_8.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_14.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_2.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_10.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_9.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_6.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_16.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_12.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_15.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/90X/signal/PU140/BsStudy_signal_PU140_5.root
END
