void bsCandList_140PU()
{
//=========Macro generated from canvas: c1/c1
//=========  (Fri May  5 12:09:51 2017) by ROOT version6.06/04
   TCanvas *c1 = new TCanvas("c1", "c1",5,58,800,700);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(-1.3,-0.2199059,4.033333,1.246133);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.15);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   
   TH1F *bsCandList__4 = new TH1F("bsCandList__4","",4,-0.5,3.5);
   bsCandList__4->SetBinContent(1,0.9995722);
   bsCandList__4->SetBinContent(2,0.0004179105);
   bsCandList__4->SetBinContent(3,9.950249e-06);
   bsCandList__4->SetMinimum(0);
   bsCandList__4->SetMaximum(1.099529);
   bsCandList__4->SetEntries(201000);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#339900");
   bsCandList__4->SetFillColor(ci);

   ci = TColor::GetColor("#339900");
   bsCandList__4->SetLineColor(ci);
   bsCandList__4->SetLineStyle(0);
   bsCandList__4->SetMarkerStyle(20);
   bsCandList__4->GetXaxis()->SetTitle("No of B_{S} Candidates");
   bsCandList__4->GetXaxis()->SetNdivisions(505);
   bsCandList__4->GetXaxis()->SetLabelFont(42);
   bsCandList__4->GetXaxis()->SetLabelOffset(0.007);
   bsCandList__4->GetXaxis()->SetLabelSize(0.05);
   bsCandList__4->GetXaxis()->SetTitleSize(0.06);
   bsCandList__4->GetXaxis()->SetTitleOffset(1.1);
   bsCandList__4->GetXaxis()->SetTitleFont(42);
   bsCandList__4->GetYaxis()->SetTitle("Events");
   bsCandList__4->GetYaxis()->SetNdivisions(505);
   bsCandList__4->GetYaxis()->SetLabelFont(42);
   bsCandList__4->GetYaxis()->SetLabelOffset(0.007);
   bsCandList__4->GetYaxis()->SetLabelSize(0.05);
   bsCandList__4->GetYaxis()->SetTitleSize(0.06);
   bsCandList__4->GetYaxis()->SetTitleOffset(1.1);
   bsCandList__4->GetYaxis()->SetTitleFont(42);
   bsCandList__4->GetZaxis()->SetLabelFont(42);
   bsCandList__4->GetZaxis()->SetLabelOffset(0.007);
   bsCandList__4->GetZaxis()->SetLabelSize(0.05);
   bsCandList__4->GetZaxis()->SetTitleSize(0.06);
   bsCandList__4->GetZaxis()->SetTitleFont(42);
   bsCandList__4->Draw("");
   
   TH1F *bsCandList__5 = new TH1F("bsCandList__5","",4,-0.5,3.5);
   bsCandList__5->SetBinContent(1,0.7111611);
   bsCandList__5->SetBinContent(2,0.2795111);
   bsCandList__5->SetBinContent(3,0.009327758);
   bsCandList__5->SetEntries(3109);
   bsCandList__5->SetLineColor(2);
   bsCandList__5->SetLineStyle(2);
   bsCandList__5->SetLineWidth(2);
   bsCandList__5->SetMarkerStyle(20);
   bsCandList__5->GetXaxis()->SetNdivisions(505);
   bsCandList__5->GetXaxis()->SetLabelFont(42);
   bsCandList__5->GetXaxis()->SetLabelOffset(0.007);
   bsCandList__5->GetXaxis()->SetLabelSize(0.05);
   bsCandList__5->GetXaxis()->SetTitleSize(0.06);
   bsCandList__5->GetXaxis()->SetTitleOffset(0.9);
   bsCandList__5->GetXaxis()->SetTitleFont(42);
   bsCandList__5->GetYaxis()->SetLabelFont(42);
   bsCandList__5->GetYaxis()->SetLabelOffset(0.007);
   bsCandList__5->GetYaxis()->SetLabelSize(0.05);
   bsCandList__5->GetYaxis()->SetTitleSize(0.06);
   bsCandList__5->GetYaxis()->SetTitleOffset(1.3);
   bsCandList__5->GetYaxis()->SetTitleFont(42);
   bsCandList__5->GetZaxis()->SetLabelFont(42);
   bsCandList__5->GetZaxis()->SetLabelOffset(0.007);
   bsCandList__5->GetZaxis()->SetLabelSize(0.05);
   bsCandList__5->GetZaxis()->SetTitleSize(0.06);
   bsCandList__5->GetZaxis()->SetTitleFont(42);
   bsCandList__5->Draw("SAME");
   
   TH1F *bsCandList__6 = new TH1F("bsCandList__6","",4,-0.5,3.5);
   bsCandList__6->SetBinContent(1,0.417074);
   bsCandList__6->SetBinContent(2,0.5770609);
   bsCandList__6->SetBinContent(3,0.005865103);
   bsCandList__6->SetEntries(3069);

   ci = TColor::GetColor("#00008f");
   bsCandList__6->SetLineColor(ci);
   bsCandList__6->SetLineWidth(2);
   bsCandList__6->SetMarkerStyle(20);
   bsCandList__6->GetXaxis()->SetNdivisions(505);
   bsCandList__6->GetXaxis()->SetLabelFont(42);
   bsCandList__6->GetXaxis()->SetLabelOffset(0.007);
   bsCandList__6->GetXaxis()->SetLabelSize(0.05);
   bsCandList__6->GetXaxis()->SetTitleSize(0.06);
   bsCandList__6->GetXaxis()->SetTitleOffset(0.9);
   bsCandList__6->GetXaxis()->SetTitleFont(42);
   bsCandList__6->GetYaxis()->SetLabelFont(42);
   bsCandList__6->GetYaxis()->SetLabelOffset(0.007);
   bsCandList__6->GetYaxis()->SetLabelSize(0.05);
   bsCandList__6->GetYaxis()->SetTitleSize(0.06);
   bsCandList__6->GetYaxis()->SetTitleOffset(1.1);
   bsCandList__6->GetYaxis()->SetTitleFont(42);
   bsCandList__6->GetZaxis()->SetLabelFont(42);
   bsCandList__6->GetZaxis()->SetLabelOffset(0.007);
   bsCandList__6->GetZaxis()->SetLabelSize(0.05);
   bsCandList__6->GetZaxis()->SetTitleSize(0.06);
   bsCandList__6->GetZaxis()->SetTitleFont(42);
   bsCandList__6->Draw("SAME");
   
   TLegend *leg = new TLegend(0.63,0.45,0.85,0.7,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("bsCandList","L1 Signal","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("bsCandList","Offline Signal","l");

   ci = TColor::GetColor("#00008f");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("bsCandList","L1 Background","f");

   ci = TColor::GetColor("#339900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#339900");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.87,0.83,"CMS");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(61);
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.87,0.78,"Phase-2 Upgrade");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.89,0.72,"Simulation Preliminary");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(52);
   tex->SetTextSize(0.0456);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.9,0.91,"(14 TeV, <PU> = 140)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.048);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
