START
dataType  Signal
studyGen    1
dumpGenInfo 0
studyOffline 0
histFile  PU140_June20/Signal_pu140_loose_baseline.root
logFile   PU140_June20/Signal_pu140_loose_baseline.out
maxEvent -1
verbosity 0
applyTrackQuality 0
trkSelCuts maxTrkEta=2.5 minTrkPt=2.0 maxTrkChi2=20 minTrkLayers=4 minTrkPSLayers=2
phiSelCuts maxTrkPairDz=1.0 maxTrkPairDxy=1.0 massLow=0.99 massHigh=1.04
bsSelCuts maxPhiPairDxy=1.0 maxPhiPairDz=1.0 minPhiPairDr=0.2 maxPhiPairDr=1.0 maxPhiTrkDr=0.12 massLow=5.27 massHigh=5.49
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_10.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_11.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_12.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_13.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_14.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_15.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_16.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_17.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_18.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_19.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_1.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_20.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_21.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_22.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_23.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_24.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_25.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_26.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_27.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_28.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_29.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_2.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_30.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_31.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_32.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_33.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_34.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_35.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_36.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_3.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_4.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_5.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_6.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_7.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_8.root
inputFile /eos/user/s/sarkar/BsStudy/Processing/920/signal/PU140/BsStudy_signal_PU140_9.root
END
